name: QUICK BUCK2 BUILD AND TEST
on: [push, pull_request, workflow_dispatch]

env:
  CPP_TIMEOUT_SEC: 5
  PY_TIMEOUT_SEC: 5

jobs:
  build:
    name: Ubuntu Linux
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          submodules: 'true'
      - name: install buck2
        uses: dtolnay/install-buck2@v1 
      - run: buck2 clean
      - run: |
            buck2 build //...
